(function(){
'use strict';
var data=window.KG_DATA;if(!data||!data.nodes||!data.nodes.length)return;
var state={domain:data.domains[0].name,selected:null,query:'',view:window.innerWidth<680?'list':'graph'},nodeBySlug={};
data.nodes.forEach(function(n){nodeBySlug[n.slug]=n});
var domainsEl=document.getElementById('kg-domains'),svg=document.getElementById('kg-svg'),listEl=document.getElementById('kg-list'),mapEl=document.getElementById('kg-map'),panelEl=document.getElementById('kg-panel'),searchEl=document.getElementById('kg-search'),graphButton=document.getElementById('kg-graph-view'),listButton=document.getElementById('kg-list-view'),continueButton=document.getElementById('kg-continue'),nextEl=document.getElementById('kg-next'),NS='http://www.w3.org/2000/svg';
function el(name,cls,text){var x=document.createElement(name);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x}
function se(name,attrs){var x=document.createElementNS(NS,name);Object.keys(attrs||{}).forEach(function(k){x.setAttribute(k,attrs[k])});return x}
function stateText(v){return{unseen:'未开始',learning:'学习中',mastered:'基本掌握',skilled:'熟练',empty:'暂无题目',anonymous:'登录后查看'}[v]||v}
function difficultyText(v){return{easy:'基础',medium:'进阶',hard:'困难'}[v]||v}
function visibleNodes(){var q=state.query.trim().toLowerCase();return data.nodes.filter(function(n){if(n.domain!==state.domain)return false;if(!q)return true;var t=n.name+' '+n.description+' '+n.tags.map(function(x){return x.name}).join(' ')+' '+(n.aliases||[]).join(' ');return t.toLowerCase().indexOf(q)!==-1})}
function renderDomains(){domainsEl.innerHTML='';data.domains.forEach(function(d){var b=el('button','kg-domain'+(state.domain===d.name?' active':''));b.type='button';b.setAttribute('aria-pressed',state.domain===d.name?'true':'false');b.appendChild(el('span','kg-domain-name',d.name));var m=el('span','kg-domain-meta');m.appendChild(el('span','',d.node_count+' 个知识点'));m.appendChild(el('span','',data.authenticated?d.mastery+'%':d.problem_count+' 题'));b.appendChild(m);var track=el('span','kg-domain-track'),fill=el('span');fill.style.width=(data.authenticated?d.mastery:Math.min(100,d.problem_count))+'%';track.appendChild(fill);b.appendChild(track);b.addEventListener('click',function(){state.domain=d.name;state.selected=null;render()});domainsEl.appendChild(b)})}
function domainEdges(nodes){var ok={};nodes.forEach(function(n){ok[n.slug]=true});return data.edges.filter(function(e){return ok[e.source]&&ok[e.target]})}
function layout(nodes,edges){var depth={};nodes.forEach(function(n){depth[n.slug]=0});for(var pass=0;pass<nodes.length;pass++){var changed=false;edges.forEach(function(e){if(e.relation!=='prerequisite')return;var next=Math.min(nodes.length-1,depth[e.source]+1);if(next>depth[e.target]){depth[e.target]=next;changed=true}});if(!changed)break}var levels={};nodes.forEach(function(n){var d=depth[n.slug];if(!levels[d])levels[d]=[];levels[d].push(n)});var keys=Object.keys(levels).map(Number).sort(function(a,b){return a-b}),sizes=keys.map(function(k){return levels[k].length}),positions={},lanes=[];keys.forEach(function(k){levels[k].sort(function(a,b){if(a.sort_order!==b.sort_order)return a.sort_order-b.sort_order;return a.name.localeCompare(b.name,'zh-CN')})});if(keys.length===1){var columns=Math.min(3,Math.max(1,nodes.length)),rows=Math.ceil(nodes.length/columns),width=Math.max(820,columns*220+120),height=Math.max(580,rows*104+150);levels[keys[0]].forEach(function(n,i){var column=i%columns,row=Math.floor(i/columns);positions[n.slug]={x:columns===1?width/2:90+column*(width-180)/(columns-1),y:rows===1?height/2:112+row*(height-180)/(rows-1)}});return{positions:positions,width:width,height:height,lanes:lanes}}var width=Math.max(920,keys.length*165+100),height=Math.max(600,Math.max.apply(null,sizes.concat([1]))*90+140);keys.forEach(function(k,ci){var items=levels[k],x=88+ci*(width-176)/(keys.length-1);lanes.push({x:x,label:ci===0?'基础层':'进阶 '+ci});items.forEach(function(n,i){positions[n.slug]={x:x,y:98+(i+.5)*(height-132)/items.length}})});return{positions:positions,width:width,height:height,lanes:lanes}}
function renderGraph(nodes){svg.innerHTML='';var edges=domainEdges(nodes),p=layout(nodes,edges),selected=state.selected;svg.setAttribute('viewBox','0 0 '+p.width+' '+p.height);var defs=se('defs'),marker=se('marker',{id:'kg-arrow',viewBox:'0 0 10 10',refX:'9',refY:'5',markerWidth:'6',markerHeight:'6',orient:'auto-start-reverse'});marker.appendChild(se('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'context-stroke'}));defs.appendChild(marker);svg.appendChild(defs);p.lanes.forEach(function(lane){var guide=se('line',{x1:lane.x,y1:'62',x2:lane.x,y2:p.height-30,class:'kg-lane'}),label=se('text',{x:lane.x,y:'36',class:'kg-lane-label'});label.textContent=lane.label;svg.appendChild(guide);svg.appendChild(label)});edges.forEach(function(e){var a=p.positions[e.source],b=p.positions[e.target];if(!a||!b)return;var active=selected&&(e.source===selected||e.target===selected),muted=selected&&!active,startX=a.x+(b.x>=a.x?74:-74),endX=b.x+(b.x>=a.x?-74:74),bend=Math.max(30,Math.abs(endX-startX)*.42),path=se('path',{d:'M'+startX+','+a.y+' C'+(startX+(b.x>=a.x?bend:-bend))+','+a.y+' '+(endX+(b.x>=a.x?-bend:bend))+','+b.y+' '+endX+','+b.y,class:'kg-edge '+e.relation+(active?' active':'')+(muted?' muted':''),'vector-effect':'non-scaling-stroke'}),title=se('title');title.textContent=e.relation==='prerequisite'?'前置知识':e.relation==='strong'?'强关联':'相关知识';path.appendChild(title);svg.appendChild(path)});nodes.forEach(function(n){var pos=p.positions[n.slug],connected=!selected||selected===n.slug||edges.some(function(e){return(e.source===selected&&e.target===n.slug)||(e.target===selected&&e.source===n.slug)}),g=se('g',{class:'kg-node '+n.progress.state+(selected===n.slug?' selected':'')+(connected?'':' muted'),transform:'translate('+pos.x+' '+pos.y+')',tabindex:'0',role:'button','aria-label':n.name+'，'+n.progress.problem_count+'道题，'+stateText(n.progress.state)});g.appendChild(se('rect',{x:'-74',y:'-30',width:'148',height:'60',rx:'11',class:'kg-node-card'}));g.appendChild(se('rect',{x:'-74',y:'-20',width:'5',height:'40',rx:'2.5',class:'kg-node-status'}));var name=se('text',{x:'-58',y:'-4',class:'kg-node-name'});name.textContent=n.name;g.appendChild(name);var count=se('text',{x:'-58',y:'16',class:'kg-node-count'});count.textContent=n.progress.problem_count+' 道题 · '+stateText(n.progress.state);g.appendChild(count);function choose(){selectNode(n.slug)}g.addEventListener('click',choose);g.addEventListener('keydown',function(event){if(event.key==='Enter'||event.key===' '){event.preventDefault();choose()}});svg.appendChild(g)})}
function renderList(nodes){listEl.innerHTML='';nodes.forEach(function(n){var b=el('button','kg-list-node');b.type='button';b.appendChild(el('strong','',n.name));b.appendChild(el('span','',n.progress.problem_count+' 道题 · '+stateText(n.progress.state)+(data.authenticated?' · 掌握度 '+n.progress.mastery+'%':'')));b.addEventListener('click',function(){selectNode(n.slug)});listEl.appendChild(b)})}
function relationGroups(node){var g={prerequisite:[],next:[],strong:[],related:[]};data.edges.forEach(function(e){if(e.relation==='prerequisite'){if(e.target===node.slug)g.prerequisite.push(nodeBySlug[e.source]);if(e.source===node.slug)g.next.push(nodeBySlug[e.target])}else if(e.source===node.slug)g[e.relation].push(nodeBySlug[e.target]);else if(e.target===node.slug)g[e.relation].push(nodeBySlug[e.source])});return g}
function appendRelations(root,title,items){items=items.filter(Boolean);if(!items.length)return;var s=el('div','kg-section');s.appendChild(el('h3','',title));var rows=el('div','kg-relations');items.forEach(function(item){var b=el('button','kg-relation',item.name);b.type='button';b.addEventListener('click',function(){state.domain=item.domain;state.selected=item.slug;render()});rows.appendChild(b)});s.appendChild(rows);root.appendChild(s)}
function problemRow(problem,recommended){var a=el('a','kg-problem');a.href='problem.php?id='+problem.id;a.appendChild(el('span','kg-problem-id',String(problem.id)));a.appendChild(el('span','kg-problem-title',problem.title));var suffix=difficultyText(problem.difficulty);if(problem.user_status==='accepted')suffix='已通过';else if(problem.user_status==='attempted')suffix=recommended?'继续挑战':'已尝试';a.appendChild(el('span','kg-problem-state',suffix));return a}
function renderPanel(){panelEl.innerHTML='';var n=state.selected?nodeBySlug[state.selected]:null;if(!n){panelEl.appendChild(el('div','kg-panel-empty','选择一个知识点，查看前置关系、掌握依据和关联题目。'));return}panelEl.appendChild(el('div','kg-panel-domain',n.domain));panelEl.appendChild(el('h2','',n.name));panelEl.appendChild(el('p','kg-description',n.description));var scores=el('div','kg-scoreline'),completion=el('div','kg-score'),mastery=el('div','kg-score');completion.appendChild(el('b','',data.authenticated?n.progress.completion+'%':'—'));completion.appendChild(el('span','','完成度 · '+n.progress.problem_count+' 道关联题'));mastery.appendChild(el('b','',data.authenticated?n.progress.mastery+'%':'—'));mastery.appendChild(el('span','','掌握度 · '+stateText(n.progress.state)));scores.appendChild(completion);scores.appendChild(mastery);panelEl.appendChild(scores);var progress=el('div','kg-progress'),fill=el('span');fill.style.width=(n.progress.mastery||0)+'%';progress.appendChild(fill);panelEl.appendChild(progress);
if(!data.authenticated){panelEl.appendChild(el('div','kg-explain','登录后可查看已尝试、已通过、分难度掌握度和下一题推荐。'));var login=el('a','kg-login','登录并查看我的进度');login.href='loginpage.php';panelEl.appendChild(login)}else{var tierSection=el('div','kg-section');tierSection.appendChild(el('h3','','掌握依据'));[['easy','基础'],['medium','进阶'],['hard','困难']].forEach(function(pair){var tier=n.progress.tiers[pair[0]],row=el('div','kg-tier');row.appendChild(el('span','',pair[1]));var track=el('div','kg-tier-track'),bar=el('span');bar.style.width=(tier.score||0)+'%';track.appendChild(bar);row.appendChild(track);row.appendChild(el('span','',tier.total?tier.accepted+'/'+tier.total:'—'));tierSection.appendChild(row)});tierSection.appendChild(el('div','kg-explain','完成度按不同已通过题目计算；掌握度按基础 40%、进阶 40%、困难 20% 加权。错误提交影响推荐顺序，不扣除已经获得的掌握度。'));panelEl.appendChild(tierSection)}
if(n.tags.length){var ts=el('div','kg-section');ts.appendChild(el('h3','','对应标准标签'));var tags=el('div','kg-tags');n.tags.forEach(function(tag){var a=el('a','kg-tag',tag.name);a.href='problemset.php?search='+encodeURIComponent(tag.name);tags.appendChild(a)});ts.appendChild(tags);panelEl.appendChild(ts)}if(n.aliases&&n.aliases.length){var as=el('div','kg-section');as.appendChild(el('h3','','兼容题目标签'));var aliases=el('div','kg-tags');n.aliases.forEach(function(name){var a=el('a','kg-tag kg-tag-alias',name);a.href='problemset.php?search='+encodeURIComponent(name);aliases.appendChild(a)});as.appendChild(aliases);panelEl.appendChild(as)}var groups=relationGroups(n);appendRelations(panelEl,'需要先掌握',groups.prerequisite);appendRelations(panelEl,'可以继续学习',groups.next);appendRelations(panelEl,'强关联知识',groups.strong);appendRelations(panelEl,'相关知识',groups.related);var candidates=n.progress.recommendations||[];if(candidates.length){var rec=el('div','kg-section');rec.appendChild(el('h3','',data.authenticated?'推荐下一题':'从这些题开始'));var rl=el('div','kg-problems');candidates.forEach(function(p){rl.appendChild(problemRow(p,true))});rec.appendChild(rl);panelEl.appendChild(rec)}var all=el('div','kg-section');all.appendChild(el('h3','','全部关联题目'));var al=el('div','kg-problems');n.progress.problems.slice(0,20).forEach(function(p){al.appendChild(problemRow(p,false))});all.appendChild(al);if(n.progress.problems.length>20)all.appendChild(el('div','kg-explain','当前展示前 20 道。可点击上方标签进入题库查看完整列表。'));panelEl.appendChild(all)}
function selectNode(slug){state.selected=slug;renderMap();renderPanel();if(window.innerWidth<1050)panelEl.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}
function renderMap(){var nodes=visibleNodes();renderGraph(nodes);renderList(nodes);mapEl.classList.toggle('list-mode',state.view==='list');graphButton.classList.toggle('active',state.view==='graph');listButton.classList.toggle('active',state.view==='list');graphButton.setAttribute('aria-pressed',state.view==='graph'?'true':'false');listButton.setAttribute('aria-pressed',state.view==='list'?'true':'false')}
function chooseNext(){var prerequisites={};data.edges.forEach(function(e){if(e.relation==='prerequisite'){if(!prerequisites[e.target])prerequisites[e.target]=[];prerequisites[e.target].push(e.source)}});function eligible(n){return!prerequisites[n.slug]||prerequisites[n.slug].every(function(slug){var p=nodeBySlug[slug];return p&&p.progress.mastery>=60})}var ranked=data.nodes.slice().sort(function(a,b){var rank={learning:0,unseen:1,mastered:2,skilled:3,empty:4,anonymous:1},ar=rank[a.progress.state]===undefined?5:rank[a.progress.state],br=rank[b.progress.state]===undefined?5:rank[b.progress.state];if(data.authenticated&&a.progress.state==='unseen'&&!eligible(a))ar=3;if(data.authenticated&&b.progress.state==='unseen'&&!eligible(b))br=3;if(ar!==br)return ar-br;if(a.progress.recommendations.length!==b.progress.recommendations.length)return b.progress.recommendations.length-a.progress.recommendations.length;return a.sort_order-b.sort_order}),next=ranked[0];nextEl.querySelector('.kg-next-label').textContent=data.authenticated?'根据你的判题记录推荐':'从知识领域开始探索';nextEl.querySelector('.kg-next-title').textContent=data.authenticated?'继续：'+next.name:'先看看：'+next.domain;nextEl.querySelector('.kg-next-copy').textContent=data.authenticated&&next.progress.recommendations.length?'优先完成你尚未通过的关联题，掌握依据会在判题后自动更新。':'浏览前置关系和真实题目；登录后将显示个人掌握度。';continueButton.onclick=function(){state.domain=next.domain;renderDomains();selectNode(next.slug)}}
function render(){renderDomains();renderMap();renderPanel()}
searchEl.addEventListener('input',function(){state.query=this.value;if(state.query.trim()){var q=state.query.trim().toLowerCase(),first=data.nodes.find(function(n){return(n.name+' '+n.description+' '+n.tags.map(function(t){return t.name}).join(' ')+' '+(n.aliases||[]).join(' ')).toLowerCase().indexOf(q)!==-1});if(first)state.domain=first.domain}state.selected=null;render()});graphButton.addEventListener('click',function(){state.view='graph';renderMap()});listButton.addEventListener('click',function(){state.view='list';renderMap()});chooseNext();render();
})();
