<?php $show_title = '反例猎人 - '.$OJ_NAME; $OJ_ADVENTURE_VIEWPORT = true; include "template/$OJ_TEMPLATE/header.php"; ?>
<link rel="stylesheet" href="template/syzoj/css/adventure.css?v=20260914.2">
<link rel="stylesheet" href="template/syzoj/css/hunt.css?v=20260914.1">
<div class="adv-page hunt-page">
  <a class="oj-back-link" href="adventure.php?tab=hunt">← 今日冒险 · 反例猎人</a>
  <header class="adv-heading"><div><h1>反例猎人</h1><p>把容易漏掉的边界，变成大家一起破解的题。</p></div><nav class="hunt-actions" aria-label="反例社区"><a href="hunt.php" <?php if (!$target && !$editing && !$mine) echo 'aria-current="page"'; ?>>社区题目</a><?php if ($user) { ?><a href="hunt.php?mode=mine">我的题目</a><a class="ui primary button" href="hunt.php?mode=new">我要出题</a><?php } else { ?><a href="loginpage.php">登录后出题</a><?php } ?></nav></header>
  <?php if ($error) { ?><p class="adv-feedback adv-error" role="alert"><?php echo adv_escape($error); ?></p><?php } ?>
  <?php if ($editing && $user && (!$id || ($challenge && $challenge['author'] === $user))) { ?>
  <section class="adv-panel"><h2><?php echo $mode === 'edit' ? '编辑题目' : '发布一道反例题'; ?></h2><p>无需审核，发布后所有人都可以挑战。三段程序使用同一种语言，通过标准输入和标准输出读写。</p>
    <form method="post" class="hunt-editor" action="hunt.php?mode=<?php echo $mode === 'edit' ? 'edit&amp;id='.$id : 'new'; ?>">
      <?php require './include/set_post_key.php'; ?><input type="hidden" name="action" value="save"><input type="hidden" name="version" value="<?php echo adv_escape($form['version']); ?>">
      <label for="hunt-title">标题 <span>最多 160 字</span></label><input id="hunt-title" name="title" maxlength="160" required value="<?php echo adv_escape(hunt_text($form,'title')); ?>">
      <label for="hunt-statement">题意与输入范围</label><textarea id="hunt-statement" name="statement" rows="6" required maxlength="16000" aria-describedby="statement-help"><?php echo adv_escape(hunt_text($form,'statement')); ?></textarea><p id="statement-help" class="adv-note">写清楚程序应该做什么、输入格式、合法范围和输出格式；最多 16 KB。</p>
      <label for="hunt-language">程序语言</label><select id="hunt-language" name="language" required><?php foreach (hunt_languages() as $lang=>$label) { ?><option value="<?php echo $lang; ?>" <?php if ((string)$form['language'] === (string)$lang) echo 'selected'; ?>><?php echo $label; ?></option><?php } ?></select>
      <?php foreach (array('buggy_source'=>'错误程序','reference_source'=>'参考程序','validator_source'=>'输入校验程序') as $key=>$label) { ?><label for="<?php echo $key; ?>"><?php echo $label; ?> <span>完整程序，最多 32 KB</span></label><textarea class="hunt-code" id="<?php echo $key; ?>" name="<?php echo $key; ?>" rows="10" maxlength="32000" spellcheck="false" required <?php if ($key==='validator_source') echo 'aria-describedby="validator-help"'; ?>><?php echo adv_escape(hunt_text($form,$key)); ?></textarea><?php } ?>
      <p id="validator-help" class="adv-note">校验程序对合法输入只输出 VALID，不合法输入只输出 INVALID。参考程序必须能处理所有合法输入。基础限制为 5 秒 / 512 MB（解释型语言按站点配置增加额度）；输出为文本，最多 16 KB。输出按空白分隔的内容比较。</p>
      <div class="hunt-actions"><button class="ui primary button" type="submit"><?php echo $mode === 'edit' ? '保存修改' : '发布题目'; ?></button><a href="<?php echo $id ? 'hunt.php?id='.$id : 'hunt.php'; ?>">取消</a></div>
      <?php if ($id) { ?><p class="adv-note">保存会产生新版本，历史挑战保留原版本的程序与结果。下架题目保存后仍保持下架。</p><?php } ?>
    </form>
  </section>
  <?php } elseif ($target) { ?>
    <?php if ($challenge) { ?>
    <section class="adv-panel"><div class="adv-section-head"><h2><?php echo adv_escape($challenge['title']); ?></h2><span><?php echo $challenge['hidden'] ? '已下架' : '公开'; ?> · 第 <?php echo intval($challenge['version']); ?> 版</span></div>
      <p class="adv-note"><?php echo adv_escape($challenge['author']); ?> 发布 · <?php echo adv_escape($challenge['created_at']); ?> · <?php echo intval($challenge['language']) === 1 ? 'C++' : 'Python 3'; ?></p>
      <div class="hunt-prose"><?php echo adv_escape($challenge['statement']); ?></div><h3>找出这段程序的破绽</h3><pre class="hunt-code"><code><?php echo adv_escape($challenge['buggy_source']); ?></code></pre>
      <?php if ($user && ($user === $challenge['author'] || $admin)) { ?><div class="hunt-actions"><?php if ($user === $challenge['author']) { ?><a class="ui basic button" href="hunt.php?mode=edit&amp;id=<?php echo $id; ?>">编辑题目</a><?php } ?><?php if (!$challenge['hidden'] || $user === $challenge['author']) { ?><form method="post" action="<?php echo adv_escape($huntUrl); ?>"><?php require './include/set_post_key.php'; ?><input type="hidden" name="action" value="visibility"><input type="hidden" name="hidden" value="<?php echo $challenge['hidden'] ? '0' : '1'; ?>"><input type="hidden" name="version" value="<?php echo intval($challenge['version']); ?>"><button class="ui basic button" type="submit"><?php echo $challenge['hidden'] ? '重新公开' : '下架题目'; ?></button></form><?php } ?></div><?php } ?>
    </section>
    <?php if (!$challenge['hidden']) { ?><section class="adv-panel"><h2>提交你的反例</h2><?php if ($user) { ?><form method="post" class="adv-hunt-form" action="<?php echo adv_escape($huntUrl); ?>"><?php require './include/set_post_key.php'; ?><input type="hidden" name="action" value="attempt"><input type="hidden" name="version" value="<?php echo intval($challenge['version']); ?>"><label for="hunt-input">反例输入</label><textarea id="hunt-input" name="input" rows="5" maxlength="8192" aria-describedby="input-help"><?php echo adv_escape(hunt_text($_POST,'input')); ?></textarea><p id="input-help" class="adv-note">最多 8 KB，可以提交空输入。校验通过后，对比错误程序与参考程序的结果；每分钟最多验证 3 次。</p><button class="ui primary button" type="submit">验证反例</button></form><?php } else { ?><p>登录后构造一组输入，看看能否让程序露出破绽。</p><a class="ui primary button" href="loginpage.php">登录并挑战</a><?php } ?></section><?php } else { ?><p class="adv-feedback">题目已下架，暂停挑战与新评论。作者可编辑后重新公开。</p><?php } ?>
    <?php if ($attempt && $outcome) { list($verdict, $jobs) = $outcome; ?><section id="attempt" class="adv-panel"><h2>我的最近挑战</h2><p class="adv-note">记录 #<?php echo intval($attempt['id']); ?> · 第 <?php echo intval($attempt['challenge_version']); ?> 版 · <?php echo adv_escape($attempt['created_at']); ?></p><p class="adv-feedback <?php if ($verdict[0] === 'hit') echo 'adv-success'; ?>" role="status"><?php echo adv_escape($verdict[1]); ?></p><?php if ($verdict[0] === 'pending' && time()-strtotime($attempt['created_at']) > 60) { ?><p class="adv-note">等待时间较长，请稍后刷新；若一直没有结果，请联系管理员检查判题服务。</p><?php } ?><?php if (intval($attempt['challenge_version']) !== intval($challenge['version'])) { ?><p class="adv-note">这是旧版本的结果，当前题目已更新。</p><?php } ?><details><summary>查看本次输入与输出</summary><h3>提交输入</h3><pre><?php echo adv_escape($attempt['input_text']); ?></pre><?php foreach (array('reference'=>'参考程序输出','buggy'=>'错误程序输出') as $role=>$label) { if (isset($jobs[$role]) && intval($jobs[$role]['result']) === 13) { ?><h3><?php echo $label; ?></h3><pre><?php echo adv_escape($jobs[$role]['output'] ?? ''); ?></pre><?php } } ?></details><a class="ui basic button" href="hunt.php?id=<?php echo $id; ?>&amp;attempt=<?php echo intval($attempt['id']); ?>#attempt">刷新验证结果</a></section><?php } ?>
    <?php } else { $h = $builtins[$builtin]; ?><section class="adv-panel"><h2><?php echo adv_escape($h['title']); ?></h2><p><?php echo adv_escape($h['rule']); ?></p><pre><code><?php echo adv_escape($h['code']); ?></code></pre><a class="ui primary button" href="adventure.php?tab=hunt&amp;hunt=<?php echo adv_escape($builtin); ?>">构造反例</a></section><?php } ?>
    <section class="adv-panel" id="comments"><h2>题目讨论</h2><p class="adv-note">交流边界情况、题意和解法。评论可能包含解题提示。</p>
      <?php if ($user && (!$challenge || !$challenge['hidden'])) { ?><form method="post" action="<?php echo adv_escape($huntUrl); ?>" class="adv-hunt-form"><?php require './include/set_post_key.php'; ?><input type="hidden" name="action" value="comment"><label for="comment-content">你的评论</label><textarea id="comment-content" name="content" rows="3" maxlength="6000" required aria-describedby="comment-help"><?php echo adv_escape(hunt_text($_POST,'content')); ?></textarea><p id="comment-help" class="adv-note">最多 6 KB；仅支持普通文字和代码。</p><button class="ui primary button" type="submit">发表评论</button></form><?php } elseif (!$user) { ?><p><a href="loginpage.php">登录</a>后加入讨论。</p><?php } ?>
      <?php if (!$comments) { ?><p class="adv-empty">还没有评论，来分享第一个思路吧。</p><?php } ?>
      <?php foreach ($comments as $comment) { ?><article class="hunt-comment"><div class="adv-section-head"><p><strong><?php echo adv_escape($comment['author']); ?></strong> <time><?php echo adv_escape($comment['created_at']); ?></time></p><?php if ($user && ($admin || $comment['author'] === $user)) { ?><form method="post" action="<?php echo adv_escape($huntUrl); ?>"><?php require './include/set_post_key.php'; ?><input type="hidden" name="action" value="delete_comment"><input type="hidden" name="comment_id" value="<?php echo intval($comment['id']); ?>"><button class="ui basic button" type="submit" aria-label="删除 <?php echo adv_escape($comment['author']); ?> 的评论">删除</button></form><?php } ?></div><div class="hunt-prose"><?php echo adv_escape($comment['content']); ?></div></article><?php } ?>
      <nav class="hunt-actions" aria-label="评论翻页"><?php if ($page > 1) { ?><a href="<?php echo adv_escape($huntUrl); ?>&amp;page=<?php echo $page-1; ?>#comments">上一页</a><?php } ?><?php if ($commentMore) { ?><a href="<?php echo adv_escape($huntUrl); ?>&amp;page=<?php echo $page+1; ?>#comments">下一页</a><?php } ?></nav>
    </section>
  <?php } elseif (!$editing) { ?>
    <section class="adv-panel"><h2><?php echo $mine ? '我发布的题目' : '社区题目'; ?></h2><?php if (!$items && !$error) { ?><p class="adv-empty"><?php echo $mine ? '你还没有发布题目。把一个容易犯的错误，变成一道有趣的挑战吧。' : '社区的第一道反例题，等你来出。也可以先挑战今日冒险中的内置题。'; ?></p><?php } ?><ul class="adv-problems"><?php foreach ($items as $item) { ?><li><a href="hunt.php?id=<?php echo intval($item['id']); ?>"><?php echo adv_escape($item['title']); ?></a><span><?php echo adv_escape($item['author']); ?> · <?php echo intval($item['language']) === 1 ? 'C++' : 'Python 3'; ?><?php if ($item['hidden']) echo ' · 已下架'; ?></span></li><?php } ?></ul><nav class="hunt-actions" aria-label="题目翻页"><?php if ($page > 1) { ?><a href="hunt.php?page=<?php echo $page-1; ?><?php if ($mine) echo '&amp;mode=mine'; ?>">上一页</a><?php } ?><?php if ($hasMore) { ?><a href="hunt.php?page=<?php echo $page+1; ?><?php if ($mine) echo '&amp;mode=mine'; ?>">下一页</a><?php } ?></nav></section>
  <?php } ?>
</div>
<?php include "template/$OJ_TEMPLATE/footer.php"; ?>
